# Use postgres/example user/password credentials
version: '2.1'

networks:
  mynet:
    name: my-shared-db-network

services:

  db:
    image: 'postgres'
    container_name: Database
    restart: 'always'
    hostname: db
    networks:
      - mynet
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      PGUSER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PORT: 5432

  app:
    build: .
    image: ilyashandulskiy/chat
    networks:
      - mynet
    restart: 'always'
    container_name: App
    ports:
      - "9090:9090"
    environment:
      DATABASE_URL: 'postgresql://postgres:password@db:5432/postgres?connect_timeout=300'
    depends_on:
      db:
        condition: service_healthy
