# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PORT: 5432

  app:
    build: .
    restart: 'always'
    ports:
      - "9090:9090"
    environment:
      DATABASE_URL: 'postgresql://postgres:password@db:5432/postgres'
    depends_on:
      - db