name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Dockerfile and Push to The Hub
      uses: beehivewarrior/docker-hub-builder@v1.0
      with:
        # The username to authenticate with dockerhub
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
        # The token to authenticate with dockerhub
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        # Name of image to publish to dockerhub, e.g. 'user/my-image'
        IMAGE_NAME: ilyashandulskiy/chat
