name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Images Build And Push
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: registry.hub.docker.com
        namespaces: ilyashandulskiy
        repository_name: chat
        user_name: ilyashandulskiy
        password: ${{ secrets.DOCKER_TOKEN }}
        image_version: latest

    - name: Docker pull
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: cd ~/chat && docker-compose stop && docker-compose rm -f && docker-compose pull
        host: 176.126.103.70
        pass: 76kz97NJGTSr
        
    - name: Docker up
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: cd ~/chat && sudo docker-compose up -d
        host: 176.126.103.70
        pass: 76kz97NJGTSr
