name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Images Build And Push
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: registry.hub.docker.com
        namespaces: ilyashandulskiy
        repository_name: chat
        user_name: ilyashandulskiy
        password: ${{ secrets.DOCKER_TOKEN }}
        image_version: latest
        
    - name: SSH command runner
      uses: Evaneos/ssh-action@v0.1.0
      with:
        # Remote host(s) to connect to
        hosts: 176.126.103.70
        commands: cd chat && docker pull ilyashandulskiy/chat:latest && docker-compose up
        user: root
        password: 76kz97NJGTSr
